# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

aabPath = '../build/app/outputs/flutter-apk/app-release.aab'
apkPath = '../build/app/outputs/flutter-apk/app-release.apk'
appID = '1:526180610767:android:ae2be982eaabbf74bffdba'

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    sh "flutter build apk --release"
    changelog = sh("git log -20 --pretty=format:%s")
    firebase_app_distribution(
      app: appID, 
      groups: 'GoldenOwl',
      android_artifact_path: apkPath,
      release_notes: changelog,
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
